WebBooks/WebBooks/urls.py
"""
1.Первое,
что нам необходимо сделать, - это определить, какую информацию мы бы хотели
показывать на наших страницах. Затем установить URL-aдpeca для получения соответствующих
ресурсов. После чего создать URL-преобразования, представления (функции
или классы) и шаблоны соответствующих страниц.

2.Сформируем
URL-aдpeca, которые понадобятся для наших страниц:
□ index/ - домашняя (индексная) страница;
□ index/Ьooks/ - список всех книг;
□ index/authors/ - список всех авторов;
□ index/Ьook/<id> - детальная информация для определенной книги со значением
первичного ключа, равным <id>. Например: /index/Ьook/3 для id = 3;
□ index/author/<id> - детальная информация для определенного автора со значением
первичного ключа, равным <id>. Например: /index/author/11 для автора с id = 11.

3.

4.

"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),  # def index(request): return HttpResponse("Глaвнaя страница сайта 'Мир книг'")

]

"""
Здесь выполнен импорт модуля settings и переменных, определяющих пути к медиафайлам,
и эти пути добавлены в диспетчер URL-aдpecoв. Здесь используется инструкция
if settings. DEBUG, т. е. подключение этих адресов будет происходить только тогда,
когда выполняется разработка и отладка программного кода.
"""
if settings.DEBUG:
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

WebBooks/catalog/urls.py
from django.urls import path
from .views import index, BookListView, BookDetailView, AuthorListView, AuthorDetailView, about, contact, \
    LoanedBooksByUserListView, edit_authors, add_author, delete, edit_author, edit_books, BookCreate, BookUpdate, BookDelete

urlpatterns = [
    path('', index, name='index'),
    #     В функции path () определен параметр narne, который уникально объявляет, что мы имеем
    # дело с частным URL-преобразованием. После такого объявления можно использовать
    # это имя для «обратного» (reverse) преобразования, т. е. для динамического создания
    # URL-aдpeca, указывающего на определенный ресурс. Например, если мы задали
    # такое символическое имя, то теперь можно ссьmаться на нашу главную страницу сайта
    # при помощи создания следующей ссьmки внутри какого-либо НТМL-шаблона:
    # <а href="{% url 'index' %}">Главная страница</а>

    path('books/', BookListView.as_view(), name='books'),
    path('books/<int:pk>', BookDetailView.as_view(), name='book-detail'),
    # Здесь угловые скобки< .. > необходимы для того, чтобы получить
    # значение из URL-aдpeca. Преобразователь int обеспечивает гарантированное получение
    # целочисленного параметра, а параметр pk (primary key- первичный ключ)
    # служит для получения идентификатора книги из БД.
    # Практически так же, как и для страницы сайта ьooks, функция path () связьmает маршрут (URL-aдpec) страницы (
    # ьooks/<int:pk>) с классом в представлении views.BookDetailView. as_ v iew () . Кроме того, здесь определено имя
    # для ссьmки на данную страницу сайта (name='book-detail').

    path('authors/', AuthorListView.as_view(), name='authors-list'),
    path('authors/<int:pk>/', AuthorDetailView.as_view(), name='authors-detail'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('mybooks/', LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('edit_authors/', edit_authors, name='edit_authors'),
    path('edit_author/<int:id>', edit_author, name='edit_author'),
    path('authors_add/', add_author, name='authors_add'),
    path('delete/<int:id>/', delete, name='delete'),
    path('edit_books/',edit_books, name='edit_books'),
    path('book/create/', BookCreate.as_view(), name="book_create"),
    path('book/update/<int:pk>', BookUpdate.as_view(), name="book_update"),
    path('book/delete/<int:pk>', BookDelete.as_view(), name="book_delete"),

]

WebBooks/catalog/models.py
"""
1.При проектировании моделей данных имеет смысл создавать самостоятельные модели
для каждого объекта. Под объектом мы будем понимать группу связанной информации.
В нашем случае очевидными объектами являются: жанры книг, сами книги, авторы,
издательства, экземпляры книг, язык.

2.определить, какие данные можно и желательно выдавать в виде списка
выбора

3.Как только будет определен перечень моделей данных (таблицы БД и поля таблиц),
нужно подумать об отношениях между моделями (между таблицами в БД). Django позволяет определять отношения «один к одному
» (конструктор OneToOneFielct), «один ко многим» (конструктор ForeignKey) и «многие
ко многим» (конструктор мanyТoManyField).

4.Минимально в каждой модели должен быть определен
стандартный метод класса для Python: _ str _ (). Это необходимо для того, чтобы
вернуть удобно читаемую строку для каждого объекта.
def str (self):
    return self.field name
Если необходимо вернуть несколько полей, то потребуется другая инструкция:
def str (self):
    return '%s, %s' % (self.field_name_l, self.field_name_2)

5.Еще один распространенный метод, который включается в модели Django, - метод
get_absolute_url (), который возвращает URL-aдpec для отображения отдельных записей
модели на веб-сайте. Если этот метод определен, то Django автоматически добавит
кнопку Просмотр на сайте на экранах редактирования записей модели (на сайте администратора).
Вот типичный шаблон для get_aЬsolute_url ():
def get_absolute_url(self):
    return reverse ( 'model-detail-view', args= [str (self. id)])

6.# Создать новую запись с помощью конструктора модели
a_record = MyModelName(my_field_name="КНИгa о вкусной еде")
# Сохраните запись в базе данных.
a_record.save()

7.Для поиска и выборки данных из БД в Django служит
объект Queryset. Это интегрирующий объект - он содержит несколько объектов,
которые можно перебирать (прокручивать). Чтобы извлечь все записи из таблицы базы
данных, вызовите метод objects.all().

8.Метод filter () позволяет отфильтровать данные для Queryset в соответствии с указанным
полем и критерием фильтрации

9.

10.


"""
from django.db import models
from django.urls import reverse  # обеспечит получение абсолютных URL-aдpecoв
from django.contrib.auth.models import User
from datetime import date

"""
формирования справочника жанров книг.
"""


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text=" Введите жанр книги",
                            verbose_name="Жанр книги")  # оно будет выводиться на экран в формах рядом с полем name.

    def __str__(self):
        return self.name  # возвращающий имя жанра, которое будет внесено в конкретную запись.


"""
справочник языков книг
"""


class Language(models.Model):
    name = models.CharField(max_length=20, help_text="Введите язык книги", verbose_name="Язык книги")

    def __str__(self):
        return self.name


"""
справочник издательств
"""


class Publisher(models.Model):
    name = models.CharField(max_length=20, help_text=" Введите наименование издательства", verbose_name="Издательство")

    def __str__(self):
        return self.name


"""
справочник, в котором будем хранить сведения об авторах книг
"""


class Author(models.Model):
    first_name = models.CharField(max_length=100, help_text="Введите имя автора", verbose_name="Имя автора")
    last_name = models.CharField(max_length=100, help_text="Введите фамилию автора", verbose_name="Фамилия автора")
    date_of_birth = models.DateField(help_text="Введите дату рождения", verbose_name="Дата рождения", null=True,
                                     blank=True)  # Это поле может содержать пустое значение (null=True), т. е. не обязательно для заполния.
    about = models.TextField(help_text="Введите сведения об авторе", verbose_name="Сведения об авторе")
    photo = models.ImageField(upload_to='images', help_text="Загрузите фото автора", verbose_name="Фото автора",
                              null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


"""
Создание модели книги
"""


class Book(
    models.Model):  # модель «Книги» связана связью «один ко многим» со следующими моделями:□ «Жанр книги»;□ «Язык книги»;□ «Издательство».
    title = models.CharField(max_length=200, help_text="Введите название книги", verbose_name="Название книги")
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, help_text="Выберите жанр для книги",
                              verbose_name="Жанр книги", null=True)  # по первичному ключу связано с моделью Genre.
    language = models.ForeignKey(Language, on_delete=models.CASCADE, help_text="Выберите язык книги",
                                 verbose_name="Язык книги", null=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, help_text="Выберите издательство",
                                  verbose_name="Издательство", null=True)
    year = models.CharField(max_length=4, help_text="Введите год издания", verbose_name="Год издания")
    authors = models.ManyToManyField(Author, help_text="Выберите автора (авторов) книги",
                                     verbose_name="Автор (авторы) книги")
    summary = models.TextField(max_length=1000, help_text="Введите краткое описание книги",
                               verbose_name="Аннотация книги")
    isbn = models.CharField(max_length=13, help_text="Должно содержать 13 символов", verbose_name="ISBN книги")
    price = models.DecimalField(decimal_places=2, max_digits=7, help_text="Введите цену книги (в рублях)",
                                verbose_name="Цена (руб.)")
    photo = models.ImageField(upload_to='images', help_text="Загрузите изображение обложки",
                              verbose_name="Изображение обложки", null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):  ## Возвращает URL-aдpec для доступа к определенному экземпляру книги
        return reverse('book-detail', args=[str(self.id)])

    def display_author(
            self):  # Для того чтобы сформировать список авторов книги, мы добавим функцию (метод) display_author в модели данных вооk. Эта функция станетформировать строку, в которой будут представлены все авторы книги.
        return ', '.join([author.last_name for author in
                          self.authors.all()])  # В этой функции организован цикл с инструкцией for. В теле цикла выбираются все авторы, связанные с данной книгой, из них формируется список, который будет возвращен в точку вызова.

    display_author.short_description = 'Авторы'


"""
Создание модели Status - состояние экземпляра книги
"""


class Status(models.Model):
    name = models.CharField(max_length=20, help_text="Введите статус экземпляра книги",
                            verbose_name="Статус экземпляра книги")

    def __str__(self):
        return self.name


"""
соэдание модели Booklnstance (экземпляр книги)
"""


class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL,
                             null=True)  # Для названия книги создано поле ьооk, значение для него будет подгружено из модели вооk, с которой имеется связь по первичному ключу.
    inv_nom = models.CharField(max_length=20, null=True, help_text="Введите инвентарный номер экземпляра",
                               verbose_name="Инвентарный номер")
    status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True,
                               help_text='Изменить состояние экземпляра',
                               verbose_name="Статус экземпляра книги")  # Для задания статуса экземпляра книги (на складе, в заказе, продана и пр.) предусмотрено поле status, значение для него будет подгружено из модели Status, с которой имеется связь по первичному ключу.
    due_back = models.DateField(null=True, blank=True, help_text="Введите конец срока статуса",
                                verbose_name="Дата окончания статуса")  # Для задания даты окончания действия статуса для экземпляра книги
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 verbose_name="Заказчик",
                                 help_text="Выберите заказчика книги")
    objects = models.Manager

    class Meta:
        ordering = [
            "due_back"]  # Для сортировки экземпляров книг создан класс меtа, при этом все экземпляры будут отсортированы по дате окоцчания действия статуса.

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book,
                             self.status)  # представляет объект Bookinstance, который будет выводить содержимое нескольких полей: название книги, ее инвентарный номер и статус.

    @property
    def is_overdue(self):    #Здесь проверяется условие - не превысило ли значение даты возврата книги текущей даты. В зависимости от значений этих дат будут возвращаться значения тrue или False.
        if self.due_back and date.today() > self.due_back:
            return True
        return False

WebBooks/catalog/forms.py
"""
1.
<form action="/team_name_url/" method="post">
<label for="team_name">Bвeдитe имя</lаЬеl>
<input id="team_name" type="text" name="name_field"
vаluе="Имя по умолчанию">
<input type="suЬmit" value="OK">
</form>
Здесь у нас только одно поле для ввода имени, но форма может иметь любое количество
элементов ввода и связанных с ними текстовых меток. Атрибут элемента type определяет,
виджет какого типа будет показан в той или иной строке. Атрибуты name и id
служат для однозначной идентификации поля в коде JavaScript, CSS и НТМL, в то время
как value содержит значение поля, когда оно показывается в первый раз. Текстовая
метка добавляется при помощи тега label ( строка с текстом Введите имя в листинге
11.24) и имеет атрибут for со з􀁞ачением идентификатора id того поля, с которым
связана эта текстовая метка.
Элемент input типа type="suЬmit" будет по умолчанию показан как кнопка ОК, нажав на
которую пользователь отправляет введенные им данные на сервер (в нашем случае -
только значение поля с идентификатором team name ). Атрибуты формы action и method
определяют, каким методом будут отправлены данные на сервер (атрибут methoct) и куда
(атрибут action).
Рассмотрим более подробно два последних элемента:
□ action - это ресурс (URL-aдpec), куда будут отправлены данные для обработки.
Если значение не установлено (т. е. значением поля является пустая строка), тогда
данные будут отправлены в представление view ( функцию или класс), которое сформировало
текущую страницу;
□ method- определяет метод отправки данных (POST или GET):
• метод POST должен использоваться тогда, когда необходимо внести изменения
в базу данных на сервере. Применение этого метода должно повысить уровень
защиты от межсайтовой подделки запроса (CSRF);
• метод GET предназначен только для форм, действия с которыми не приводят
к изменению базы данных (например, для поисковых запросов). Кроме того, этот
метод рекомендуется применять для создания внешних ссылок на ресурсы сайта.

2.Итоговая форма при использовании класса ModelForm() будет содержать те же поля, что
подключенная модель данных. Все, что необходимо сделать внутри создаваемого класса,
- это добавить класс меtа и связать его с моделью. А затем в поле fields указать
поля модели данных, которые необходимо включить в форму.


"""

from django import forms
from datetime import date
from .models import Author
from .models import Book


class AuthorForm(forms.Form):
    first_name = forms.CharField(label="Имя автора") #будет генерировать на НТМLстранице текстовое поле input type="text";
    last_name = forms.CharField(label="Фамилия автора")
    date_of_birth = forms.DateField(
        label="Дата рождения",
        initial=date.today(),
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    about = forms.CharField(
        label="Сведения об авторе",
        widget=forms.Textarea
    )
    photo = forms.ImageField(label="Фото автора")




class Form_edit_author(forms.ModelForm): #Так как эта форма связана
# с моделью данных, то поля для формы определять не нужно, они будут подключены
# к форме автоматически, т. е. программный код за счет класса forms.ModelForm значительно
# упрощается.
    """
    Здесь сначала бьша импортирована модель данных с информацией об
авторах (from models irrport Author). Затем в классе Form_edit_author создан подкласс Meta,
в котором всего две строки,:
□ model = Author - создан объект moctel на основе модели данных Author;
□ fielcts = ' all ' - подключены все поля, которые имеются в модели данных об
авторах.
    """
    class Meta:
        model = Author
        fields = '__all__'  # Все поля модели Author




class BookModelForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'  # Включить все поля модели Book в форму

WebBooks/templates/catalog/author_detail.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container text-start">
    <div class="row my-2">
        <h4>{{ object.first_name }} {{ object.last_name }}</h4>
        <p>Родился - {{ object.date_of_birth }}</p>
        <p>Фото (портрет)</p>
        <p><img src="{{ object.photo.url }}" alt="Фото" style="max-height:200px"></p>
    </div>
    <div class="row my-2">
        <div class="col-2 my-2">
            <a href="{{ object.photo.url }}" class="btn btn-primary" target="_blank">Показать</a>
        </div>
    </div>
    <div class="row my-2">
        {{ object.about }}
    </div>
</div>
{% endblock %}

WebBooks/templates/catalog/author_list.html
{% extends "catalog/base.html" %}
{% block content %}
<h4>Список авторов книг</h4>
{% if author_list %}
<table class="table table-striped table-bordered text-start">
    <thead>
        <tr>
            <th>Автор</th>
            <th>Фото</th>
            <th>Показать фото</th>
        </tr>
    </thead>
    <tbody>
        {% for author in author_list %}
        <tr>
            <td><a href="{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</a></td>
            <td><img src="{{ author.photo.url }}" alt="Фото" style="max-height: 100px;"></td>
            <td><a href="{{ author.photo.url }}" class="btn btn-primary" target="_blank">Показать</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>В базе данных нет авторов</p>
{% endif %}
{% endblock content %}

WebBooks/templates/catalog/authors_add.html
{% extends "catalog/base.html" %}
{% block content %}
<h5>Добавить в БД автора книги</h5>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
      <table class="table text-start">
        {{ form.as_table }}
      </table>
    </div>
    <div class="col-2"></div>
  </div>
  <input type="submit" value="Сохранить">
</form>
{% endblock content %}

WebBooks/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>

    <!--  В этом блоке через тег Django { % loact static % J сделана ссылка на папку static, в которой-->
    <!--содержатся статические файлы. В эту папку мы поместили изображения и файлы-->
    <!--фреймворка Bootstrap. В этом же блоке файлы Bootstrap подключены к базовому шаблону-->
    <!--нашего сайта-->

    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


    <!--    <link rel="stylesheet" href="/static/scss/bootstrap.min.css">-->
    <!--    <script defer src="/static/js/bootstrap.bundle.min.js' %}"></script>-->
</head>
<body>

<!--В этом блоке создано четыре адаптивных-->
<!--контейнера Bootstrap class="container-fluid" для размещения:-->
<!--□ шапки сайта;-->
<!--□ навигационной панели с главным (верхним) меню сайта;-->
<!--□ основного контента;-->
<!--□ «подвала» страниц сайта.-->

<div class="container-fluid py-1 bg-primary text-white text-center">
    <!--      В первом контейнере находится, так называемая шапка сайта. Этот контейнер имеет-->
    <!--одну строку и две колонки. В первой колонке вьmеден логотип сайта (это изображение-->
    <!--из папки static) и строка с названием сайта.-->
    <div class="row">
        <div class="col-2 text-start">
            <img src="{% static 'images/pp100.jpg' %}" width="70" height="70" alt="Логотип">
        </div>
        <div class="col-10">
            <h3>Мир книг - печатные и электронные антерактивные книги</h3>
        </div>
    </div>
</div>

<div class="container-fluid">
    <!--      Во втором контейнере создана одна строка, в которой находится навигационная панель-->
    <!--сайта. В этой строке пока мы поместили ссылки на три страницы сайта: «Главная страница-->
    <!--», «О компании», «Контакты». Так как страницы «О компании», «Контакты» еще-->
    <!--не созданы, то для них временно указаны адреса главной страницы - { % ur 1 'index' % J.-->
    <div class="row bg-warning text-center">
        <h3>
            <a href="{% url 'index' %}">Главная страница</a>
            <a href="{% url 'about' %}">О компании</a>
            <a href="{% url 'contact' %}">Контакты</a>
        </h3>
    </div>
</div>


<!--В третьем контейнере созданы две строки, при этом вторая строка разбита на две колонки.-->
<!--В первой строке находится блок для размещения заголовка страницы - { % Ыосk-->
<!--header% J. В первой колонке второй строки находится блок «боковая панель» - { % Ыосk-->
<!--sictebar %}, в которой будет выводиться дополнительное (боковое) меню сайт􀂞. Во вто-
 рой колонке второй строки находится блок с основным контентом страницы - 1 % Ыосk
content % J, в котором будет выводиться основное содержание страницы сайта.-->
<div class="container-fluid">
    <div class="row text-center text-primary fs-1 fw-bold">
        <div>{% block header %}{% endblock header %}</div>
    </div>
</div>
<div class="row text-center text-body">
    <div class="col-2">
        {% block sidebar %}
        <nav class="nav flex-column">
            <a class="nav-link" href="{% url 'books' %}">Все книги</a> <!-- В этой строке мы указали, что при выборе опции меню Все книги будет выполнен переход
к URL-преобразованию с именем 'books ', а в нем происходит обращение к классу вookListView, который и вьmолнит всю работу по заполнению шаблона book_list.html и его
отправке пользователю.-->
            <a class="nav-link" href="{% url 'authors-list' %}">Все авторы</a>

            <!--            Блок проверки входа/выхода пользователя на сайт-->
            <!--в боковой панели базового шаблона-->

            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}?next={{request.path}}">Выйти</a> <!-- После успешного
входа пользователя в систему представления будут использовать значение next, чтобы
при выходе из системы перенаправить пользователя обратно на страницу, с которой он
входил в систему.-->
            <div>Вошел: {{ user.get_username }}</div> <!-- Если пользователь аутентифицирован, то мы знаем, что это вошел зарегистрированный
пользователь, поэтому вызываем { {user.get_username} }, чтобы отобразит.ь его имя.-->

            <a class="nav-link" href="{% url 'edit_authors' %}">Редактор авторов</a>
            <a class="nav-link" href="{% url 'edit_books' %}">Редактировать книги</a>
            <a class="nav-link" href="{% url 'my-borrowed' %}">Мои заказы</a>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Войти</a>
            {% endif %}
        </nav>
        {% endblock sidebar %}
    </div>
    <div class="col-10">
        <div class="row text-center">
            {% block content %}{% endblock content %}


            <div class="pagination">
                <!--
В этом коде сначала выполняется проверка, что число вьmодимых страниц больше
одной ( if page_ o bj .p aginator.n шnp ages > 1) . Если число выводимых страниц меньше или
равно единице, то выводимый список нет смысла разбивать на страницы. Если же список
не помещается на одной странице, то далее делается проверка, вюпочен ли механизм
постраничного вывода. Если разбивка списка на страницы включена, то после
вьmода первой страницы списка отображаются следующие элементы:
□ номер текущей страницы (page_obj .numЬer);
□ общее число страниц (page_ obj. p aginator. ni.дnp ages) ;
□ надписи со ссылками на страницы Следующая и Предыдущая.
Здесь параметр page_obj является объектом типа Paginator, который станет создаваться
каждый раз, когда будет применяться постраничный вывод данных для текущей страницы.
Он позволяет получить всю информацию о текущей странице, о предыдущих
страницах, об общем числе страниц и т. п.
В теле класса pagination есть два блока с инструкцией н:
□ { % if page obj . has previous % ) - проверка, поступил ли запрос на переход к предыдущей
странице;
□ { % if page obj . has next % ) - проверка, поступил ли запрос на переход к следующей
странице.
Если условие проверки соблюдается, то выполняется переход к заданной странице.
Здесь используем выражение _<href="?page=> для получения URL-aдpeca нужной страницы.


-->
                <span class="step-links">
                    {% if page_obj.paginator.num_pages > 1 %}
                    {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; Первая</a>
                    <!-- Как только в базе данных появится более трех записей, представление начнет формировать
постраничный вьmод данных (страницы будут передаваться шаблону). К раз-личным страницам можно будет получить доступ при помощи параметров GЕТзапроса.
Например, к странице 2 можно получить доступ через URL-aдpec /catalog/
books/?page=2. -->
                    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                    {% endif %}
                    <span class="current">
                        Стр. {{page_obj.number}}
                        из {{page_obj.paginator.num_pages}}.
                    </span>
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">Предыдушая &raquo;</a>
                    {% endif %}
                    {% endif %}
                </span>

            </div>

        </div>
    </div>
</div>
<div class="container-fluid">
    <!--      В четвертом контейнере создана одна строка, которая представляет собой «подвал»-->
    <!--( footer) страницы - { % Ыосk footer % } •-->
    <div class="row bg-primary text-center text-white lh-1">
        {% block footer %}
        <p>Copyright OOO "Петрушка", 2023. Все права защищены </p>
        {% endblock footer %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

WebBooks/templates/catalog/bookinstance_list_borrowed_user.html
<!--Здесь сначала проверяется условие- есть ли заказы у данного пользователя,-->
<!--т. е. не пустой ли список заказов { % if bookinstance _ list % ) • Если список заказов-->
<!--пуст, то выводится сообщение «Нет книг со статусом В ЗАКАЗЕ». Если у пользователя-->
<!--есть заказы, то организуется цикл for, в котором выдается информация о заказанных-->
<!--книгах - {% for bookinst in bookinstance_list %). Обратите внимание, что в теле цикла-->
<!--есть инструкция if для проверки условия, не просрочен ли заказ- {% if bookinst.-->
<!--is overdue %) . Если заказ окажется просроченным, то информация о нем (дата возврата-->
<!--книги) будет показана красным цветом (text-danger). А название книги, которая находится-->
<!--в заказе, представляет собой ссылку на страницу с информацией об этой книге:-->
<!--href="{% url 'book-detail' bookinst.book.pk %)"-->
<!--Для установления факта, что заказ просрочен, здесь предусмотрен метод is overdue,-->
<!--который создан в модели экземпляров книг:-->
<!--{% if bookinst.is_overdue %)-->

{% extends "catalog/base.html" %}
{% block content %}
<h1>Взятые книги</h1>
{% if bookinstance_list %}
<ul>
    {% for bookinst in bookinstance_list %}
    <li
    {% if bookinst.is_overdue %} class="text-danger"{% endif %}>
    <a href="{% url 'book-detail' bookinst.book.pk %}">
        {{ bookinst.book.title }}
    </a>
    {{ bookinst.due_back }}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Нет книг со статусом "В ЗАКАЗЕ".</p>
{% endif %}
{% endblock %}